# Generated by Django 3.2.4 on 2021-07-02 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirmpassword',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
