# Generated by Django 3.2.4 on 2021-07-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customer_confirmpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='confirmpassword',
            field=models.CharField(max_length=200),
        ),
    ]
